version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"  # Accede a la app en http://localhost:8000
    volumes:
      - .:/var/www/html
      - ./.env:/var/www/html/.env
    networks:
      - laravel_network
    environment:
      - "APP_ENV=local"
      - "APP_KEY=base64:V6gI1T4fHSKlFkOaMdpw4mNx1Qmz5B26tE0iHVJOM68="  # Cambia este APP_KEY si es necesario
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
    ports:
      - "3306:3306"

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
